package rules;

import com.springprojects.droolengine.model.Order;

dialect "mvel";

rule "MASTERCARD"
    when
        orderObject : Order(cardType == "MASTERCARD" && price > 10000)
    then
        System.out.println("MASTERCARD discount has been added");
        orderObject.setDiscount(10);
end;

rule "VISA"
    when
        orderObject : Order(cardType == "VISA" && price > 5000)
    then
        System.out.println("VISA discount has been added");
        orderObject.setDiscount(14);
end;

rule "AMEX
    when
        orderObject : Order(cardType == "AMEX" && price > 7000)
    then
        System.out.println("AMEX discount has been added");
        orderObject.setDiscount(18);"
end;